# Generated by Django 5.1.7 on 2025-03-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FatorClimatico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("analgésico", "Analgésico"),
                            ("antiinflamatorio", "Anti-inflamatório"),
                            ("anticonvulsivante", "Anticonvulsivante"),
                            ("neuromodulador", "Neuromodulador"),
                            ("antidepressivo", "Antidepressivo"),
                            ("ansiolítico", "Ansiolítico"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Medicamentos",
            },
        ),
        migrations.CreateModel(
            name="Sintoma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("descricao", models.CharField(max_length=100)),
                ("categoria", models.ManyToManyField(to="epione.categoria")),
            ],
            options={
                "verbose_name_plural": "Sintomas",
            },
        ),
        migrations.CreateModel(
            name="Doenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cid", models.CharField(max_length=10, unique=True)),
                ("descricao", models.TextField()),
                (
                    "sintomas",
                    models.ManyToManyField(related_name="doencas", to="epione.sintoma"),
                ),
            ],
            options={
                "verbose_name_plural": "Doenças",
            },
        ),
    ]
