# Generated by Django 5.1.7 on 2025-03-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epione", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sintoma",
            name="categoria",
        ),
        migrations.AddField(
            model_name="sintoma",
            name="categorias",
            field=models.ManyToManyField(
                related_name="sintomas", to="epione.categoria"
            ),
        ),
    ]
