# Generated by Django 5.1.7 on 2025-04-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epione", "0002_remove_sintoma_categoria_sintoma_categorias"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sintoma",
            name="categorias",
        ),
        migrations.RemoveField(
            model_name="doenca",
            name="sintomas",
        ),
        migrations.DeleteModel(
            name="Especialidade",
        ),
        migrations.DeleteModel(
            name="FatorClimatico",
        ),
        migrations.DeleteModel(
            name="Medicamento",
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.DeleteModel(
            name="Doenca",
        ),
        migrations.DeleteModel(
            name="Sintoma",
        ),
    ]
