# Generated by Django 5.1.7 on 2025-03-28 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("particular", "Particular"),
                            ("convenio", "Convênio"),
                            ("retorno", "Retorno"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("marcada", "Marcada"),
                            ("realizada", "Realizada"),
                            ("cancelada", "Cancelada"),
                            ("remarcacao_pendente", "Remarcação Pendente"),
                            ("confirmada", "Confirmada"),
                        ],
                        default="marcada",
                        max_length=30,
                    ),
                ),
                ("is_telemedicina", models.BooleanField(default=False)),
                ("link_telemedicina", models.URLField(blank=True, null=True)),
                (
                    "metodo_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("credito", "Crédito"),
                            ("debito", "Débito"),
                            ("pix", "Pix"),
                            ("dinheiro", "Dinheiro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("pagamento_confirmado", models.BooleanField(default=False)),
                ("confirmado_pelo_paciente", models.BooleanField(default=False)),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultas_canceladas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consulta_original",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retornos",
                        to="consultas.consulta",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas_medico",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas_paciente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
