# Generated by Django 5.1.7 on 2025-03-28 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0002_alter_consulta_medico"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("agendamento", "Agendamento"),
                            ("cancelamento", "Cancelamento"),
                            ("presenca", "Presença Confirmada"),
                            ("remarcacao_solicitada", "Remarcação Solicitada"),
                            ("remarcacao_aprovada", "Remarcação Aprovada"),
                            ("no_show", "Faltou"),
                        ],
                        max_length=30,
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="consultas.consulta",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("mensagem", models.TextField()),
                ("lida", models.BooleanField(default=False)),
                ("enviada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketReembolso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=8)),
                ("percentual_reembolso", models.IntegerField(default=100)),
                (
                    "metodo_pagamento",
                    models.CharField(
                        choices=[
                            ("pix", "Pix"),
                            ("credito", "Crédito"),
                            ("debito", "Débito"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motivo", models.TextField(blank=True, null=True)),
                ("aprovado", models.BooleanField(null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="consultas.consulta",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
