# Generated by Django 5.1.7 on 2025-03-28 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0003_eventoconsulta_notificacao_ticketreembolso"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketConciliacaoFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_consulta", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "metodo_pagamento",
                    models.CharField(
                        choices=[
                            ("pix", "Pix"),
                            ("credito", "Crédito"),
                            ("debito", "Débito"),
                            ("dinheiro", "Dinheiro"),
                            ("convenio", "Convênio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("conciliado", models.BooleanField(default=False)),
                ("data_conciliacao", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consulta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conciliacao",
                        to="consultas.consulta",
                    ),
                ),
            ],
        ),
    ]
