# Generated by Django 5.1.7 on 2025-03-28 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0004_ticketconciliacaofinanceira"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepasseMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pagamento_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "percentual_repasse",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "valor_total_consulta",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "valor_repassado",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("descricao_desconto", models.TextField(blank=True, null=True)),
                ("confirmado", models.BooleanField(default=False)),
                ("data_confirmacao", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "consulta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repasse",
                        to="consultas.consulta",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repasse_medico",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
