# Generated by Django 5.1.7 on 2025-03-28 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0005_repassemedico"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "introducao_gerada",
                    models.TextField(
                        blank=True,
                        help_text="Resumo automático que pode ser editado ou descartado.",
                    ),
                ),
                (
                    "descricao_complementar",
                    models.TextField(blank=True, help_text="Texto livre do médico."),
                ),
                (
                    "cid10",
                    models.CharField(
                        blank=True,
                        help_text="CID-10 da condição principal.",
                        max_length=20,
                    ),
                ),
                (
                    "exames_solicitados",
                    models.TextField(
                        blank=True, help_text="Descrição dos exames solicitados."
                    ),
                ),
                (
                    "tratamento_orientado",
                    models.TextField(
                        blank=True,
                        help_text="Conduta e orientações passadas ao paciente.",
                    ),
                ),
                (
                    "visivel_para_paciente",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, o paciente poderá ver esse relatório.",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "consulta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatorio",
                        to="consultas.consulta",
                    ),
                ),
            ],
        ),
    ]
