# Generated by Django 5.1.7 on 2025-04-01 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0006_relatorioconsulta"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceitaMedica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo", models.TextField()),
                ("visivel_para_paciente", models.BooleanField(default=False)),
                (
                    "arquivo_pdf",
                    models.FileField(blank=True, null=True, upload_to="receitas/"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "consulta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultas.consulta",
                    ),
                ),
            ],
        ),
    ]
