# Generated by Django 5.1.7 on 2025-04-03 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultas", "0007_receitamedica"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relatorio", models.TextField()),
                ("cid", models.CharField(blank=True, max_length=20, null=True)),
                ("exames_solicitados", models.TextField(blank=True)),
                ("tratamento_recomendado", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "consulta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atendimento",
                        to="consultas.consulta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("receita", "Receita"),
                            ("atestado", "Atestado"),
                            ("laudo", "Laudo"),
                            ("declaracao", "Declaração"),
                        ],
                        max_length=20,
                    ),
                ),
                ("conteudo", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "atendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="atendimento.atendimento",
                    ),
                ),
            ],
        ),
    ]
