# Generated by Django 5.1.7 on 2025-04-03 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendimento", "0001_initial"),
        ("consultas", "0007_receitamedica"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentoconsulta",
            name="atendimento",
        ),
        migrations.AddField(
            model_name="atendimento",
            name="link_telemedicina",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentoconsulta",
            name="consulta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultas.consulta",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="documentoconsulta",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("receita", "Receita Médica"),
                    ("atestado", "Atestado Médico"),
                    ("declaracao", "Declaração de Comparecimento"),
                    ("relatorio", "Relatório Clínico"),
                ],
                max_length=20,
            ),
        ),
    ]
