# Generated by Django 5.1.7 on 2025-04-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendimento", "0002_remove_documentoconsulta_atendimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atendimento",
            name="inicio_telemedicina",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
