# Generated by Django 5.1.7 on 2025-04-06 00:13

import fichamedica.models.documentos
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alergia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Anamnese",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sintomas",
                    models.JSONField(
                        default=list, help_text="Selecione entre 3 a 5 sintomas."
                    ),
                ),
                ("periodo", models.CharField(blank=True, max_length=20, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cirurgia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("cardiaca", "Cardíaca"),
                            ("ortopedica", "Ortopédica"),
                            ("neurologica", "Neurológica"),
                            ("oftalmologica", "Oftalmológica"),
                            ("ginecologica", "Ginecológica"),
                            ("digestiva", "Digestiva"),
                            ("respiratoria", "Respiratória"),
                            ("renal", "Renal"),
                            ("outra", "Outra"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[
                            ("<6m", "Menos de 6 meses"),
                            ("6m-1a", "6 meses a 1 ano"),
                            ("1-3a", "1 a 3 anos"),
                            (">3a", "Mais de 3 anos"),
                            ("dk", "Desconhecido"),
                        ],
                        max_length=10,
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DadosMedicos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacoes_gerais", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DoencaCronica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Exame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("sangue", "Exame de Sangue"),
                            ("urina", "Exame de Urina"),
                            ("fezes", "Exame de Fezes"),
                            ("glicose", "Glicose"),
                            ("imagem", "Imagem (Raio-X, Tomografia, etc)"),
                            ("colesterol", "Colesterol"),
                            ("hormonal", "Hormonal"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[
                            ("ate_6_meses", "Entre 1 e 6 meses"),
                            ("mais_6_meses", "Mais de 6 meses"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=fichamedica.models.documentos.exame_upload_path
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoFamiliar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parentesco",
                    models.CharField(
                        choices=[
                            ("pai", "Pai"),
                            ("mae", "Mãe"),
                            ("avo", "Avô/Avó"),
                            ("irmao", "Irmão/Irmã"),
                            ("filho", "Filho/Filha"),
                            ("outro", "Outro"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("pressao", "Pressão"),
                            ("humor", "Estabilizante de Humor"),
                            ("diabetes", "Diabetes"),
                            ("colesterol", "Colesterol"),
                            ("cardiaco", "Cardíaco"),
                            ("ansiolitico", "Ansiolítico"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
