# Generated by Django 5.1.7 on 2025-04-06 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fichamedica", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anamnese",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anamnese",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dadosmedicos",
            name="alergias",
            field=models.ManyToManyField(blank=True, to="fichamedica.alergia"),
        ),
        migrations.AddField(
            model_name="dadosmedicos",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dados_medicos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cirurgia",
            name="dados_medicos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cirurgias",
                to="fichamedica.dadosmedicos",
            ),
        ),
        migrations.AddField(
            model_name="dadosmedicos",
            name="doencas_cronicas",
            field=models.ManyToManyField(blank=True, to="fichamedica.doencacronica"),
        ),
        migrations.AddField(
            model_name="exame",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exames",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicofamiliar",
            name="doenca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fichamedica.doencacronica",
            ),
        ),
        migrations.AddField(
            model_name="historicofamiliar",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historico_familiar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dadosmedicos",
            name="medicamentos_em_uso",
            field=models.ManyToManyField(blank=True, to="fichamedica.tipomedicamento"),
        ),
    ]
